### ISSUE TITLE
General url parsing doesn't work

### ISSUE THREAD

**Issue by FletcherAU** [Perth-Artifactory/queryBot#5]
!url-https://raw.githubusercontent.com/Perth-Artifactory/queryBot/main/README.md caused the bot to hang.

**Comment by FletcherAU** [comment]
```Failed to run listener function (error: 'title')
Traceback (most recent call last):
  File "/home/fletcher/.local/lib/python3.8/site-packages/slack_bolt/listener/thread_runner.py", line 124, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/home/fletcher/.local/lib/python3.8/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "./slack.py", line 56, in tagged
    gpt_response = gpt.respond(prompts=struct)
  File "/home/fletcher/queryBot/gpt.py", line 47, in respond
    extras.append(optional[option](command_search[0]))
  File "/home/fletcher/queryBot/data/matryoshka.py", line 82, in single_page
    return {"role": "user", "content": f'There is a webpage titled {p["title"]} at {p["url"]} It contains:\n{p["content"]}'}
KeyError: 'title'```
